#include "facts.h"
#include <kb.h>

KB_DEFMESSAGELIST (Fact_Bees,
	"Bees have 5 eyes (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Bees are insects, so they have 6 legs (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Male bees in the hive are called drones (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Bees fly about 20 mph (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Female bees in the hive (except the queen) are called worker bees (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Number of eggs laid by queen: 2,000 per day is the high (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Losing its stinger will cause a bee to die (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Bees have been here about 30 million years (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Bees carry pollen on their hind legs in a pollen basket or corbicula (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"An average beehive can hold around 50,000 bees (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Foragers must collect nectar from about 2 million flowers to make 1 pound of honey (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"The average forager makes about 1/12 th of a teaspoon of honey in her lifetime (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Average per capita honey consumption in the US is 1.3 pounds (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Bees have 2 pairs of wings (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"The principal form of communication among honey bees is through chemicals called pheromones (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"Bees are important because they pollinate approximately 130 agricultural crops in the US including fruit, fiber, nut, and vegetable crops. Bee pollination adds approximately 14 billion dollars annually to improved crop yield and quality. (https://honeybeenet.gsfc.nasa.gov/Honeybees/Basics.htm)",
	"The honey bee has been around for millions of years. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"Honey bees, scientifically also known as Apis mellifera, which mean “honey-carrying bee”, are environmentally friendly and are vital as pollinators. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"Honey bees are the only insect that produces food eaten by man. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"Honey bees have 6 legs, 2 compound eyes made up of thousands of tiny lenses (one on each side of the head), 3 simple eyes on the top of the head, 2 pairs of wings, a nectar pouch, and a stomach. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"Honey bees have 170 odorant receptors, compared with only 62 in fruit flies and 79 in mosquitoes. Their exceptional olfactory abilities include kin recognition signals, social communication within the hive, and odor recognition for finding food. Their sense of smell is so precise that it could differentiate hundreds of different floral varieties and tell whether a flower carried pollen or nectar from metres away. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"The honey bee’s wings stroke incredibly fast, about 200 beats per second, thus making their famous, distinctive buzz. A honey bee can fly for up to six miles, and as fast as 15 miles per hour. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"The average worker bee produces only about 1/12th teaspoon of honey in her lifetime. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"A hive of bees will fly 90,000 miles, the equivalent of three orbits around the earth to collect 1 kg of honey. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"A honey bee visits 50 to 100 flowers during a collection trip. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"The bee’s brain is oval in shape and only about the size of a sesame seed (iflscience.com), yet it has remarkable capacity to learn and remember things and is able to make complex calculations on distance travelled and foraging efficiency. (https://www.benefits-of-honey.com/honey-bee-facts/)",
	"A colony of bees consists of 20,000-60,000 honeybees and one queen. Worker honey bees are female, live for about 6 weeks and do all the work. (https://www.benefits-of-honey.com/honey-bee-facts/)"
);
